feat(docs) Перевод Nuxt 3 Beta
translation-gang/nuxt.com pull request #53
Opened 2024-06-30 13:23 UTC by Ibochkarev

feat(docs) Перевод Nuxt 3 Beta

2024-06-30 15:15 UTC, Hekikai requested changes

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +description: "Спустя 468 дней после первого коммита, наконец-то появилась бета-версия Nuxt 3. Узнайте, что в ней содержится и что от нее можно ожидать. Да, она включает в себя Vue 3 и Vite. ⚡️"
```suggestion
description: "Спустя 468 дней после первого коммита наконец-то появилась бета-версия Nuxt 3. Узнайте, что в ней содержится и что от нее можно ожидать. Да, она включает в себя Vue 3 и Vite. ⚡️"
```

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +  - name: Себастьен Шопен
```suggestion
  - name: Себастьян Шопен
```

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +Документация доступна по следующему адресу: <https://nuxt.com>.
Зачем здесь кавычки, которых не было?

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +В режиме продакшена Nuxt 3 компилирует ваше приложение Vue и сервер в одну универсальную директорию `.output`. Этот вывод легкий: минифицированный и без любых других зависимостей Node.js (за исключен
```suggestion
В режиме продакшена Nuxt 3 компилирует ваше приложение Vue и сервер в одну универсальную директорию `.output`. Этот билд легкий: минифицированный и без любых других зависимостей Node.js (за исключением полифиллов). Вы можете развернуть этот билд на любой системе, поддерживающей JavaScript, будь то Node.js, Serverless, Workers, Edge-side rendering или чисто статический.
```

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +**Не используйте ее для производства до выхода первого кандидата в релиз.**
```suggestion
**Не используйте ее для продакшена до выхода первого релиз-кандидата.**
```

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +Во время бета-тестирования практически каждый коммит будет [будет запускать новый релиз](https://github.com/nuxt/nuxt/blob/main/.github/workflows/ci.yml#L111-L119). Dы можете захотеть посмотреть [при
```suggestion
Во время бета-тестирования практически каждый коммит будет [будет запускать новый релиз](https://github.com/nuxt/nuxt/blob/main/.github/workflows/ci.yml#L111-L119). Вы можете захотеть посмотреть [принятые PR](https://github.com/nuxt/nuxt/pulls?q=is%3Apr+is%3Amerged), пока мы не начнем генерировать автоматические журналы изменений в документации.
```

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +
```suggestion
```

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +- **20 мая, 2021**: [`app.vue`](https://nuxt.com/docs/guide/directory-structure/app) поддержка (`pages/` становится опциональной)
```suggestion
- **20 мая, 2021**: поддержка [`app.vue`](https://nuxt.com/docs/guide/directory-structure/app) (`pages/` становится опциональной)
```

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +На данный момент мы объединили [385 pull-запросов](https://github.com/nuxt/nuxt/pulls?q=is%3Apr+is%3Amerged), закрыли [229 проблем](https://github.com/nuxt/nuxt/issues?q=is%3Aissue+is%3Aclosed) и сде
```suggestion
На данный момент мы объединили [385 PR](https://github.com/nuxt/nuxt/pulls?q=is%3Apr+is%3Amerged), закрыли [229 проблем](https://github.com/nuxt/nuxt/issues?q=is%3Aissue+is%3Aclosed) и сделали [925+ коммитов](https://github.com/nuxt/nuxt/commits/main).
```

2024-06-30 15:15 UTC, Hekikai commented on content/7.blog/4.nuxt3-beta.md
> +Не забудьте подписаться на нас в [Твиттере](https://twitter.com/nuxt_js), чтобы получать последние новости о Nuxt!
```suggestion
Не забудьте подписаться на нас в [X](https://twitter.com/nuxt_js), чтобы получать последние новости о Nuxt!
```

2024-06-30 15:22 UTC, Ibochkarev commented on content/7.blog/4.nuxt3-beta.md
> +Документация доступна по следующему адресу: <https://nuxt.com>.
Это маркдаун формат ссылки

2024-07-01 07:09 UTC, Hekikai approved these changes

2024-07-01 07:19 UTC, alexeyvokin commented on content/7.blog/4.nuxt3-beta.md
> +В режиме продакшена Nuxt 3 компилирует ваше приложение Vue и сервер в одну универсальную директорию `.output`. Этот билд легкий: минифицированный и без любых других зависимостей Node.js (за исключени
```suggestion
В режиме продакшена Nuxt 3 компилирует ваше приложение Vue и сервер в одну универсальную директорию `.output`. Этот билд легкий: минифицированный и без любых других зависимостей Node.js (за исключением полифиллов). Вы можете развернуть этот билд на любой системе, поддерживающей JavaScript, будь то Node.js, Serverless, Workers, Edge-side rendering или только статику.
```

2024-07-01 07:19 UTC, alexeyvokin commented on content/7.blog/4.nuxt3-beta.md
> +Во время бета-тестирования практически каждый коммит будет [будет запускать новый релиз](https://github.com/nuxt/nuxt/blob/main/.github/workflows/ci.yml#L111-L119). Вы можете захотеть посмотреть [при
```suggestion
Во время бета-тестирования практически каждый коммит будет [запускать новый релиз](https://github.com/nuxt/nuxt/blob/main/.github/workflows/ci.yml#L111-L119). Вы можете захотеть посмотреть [принятые PR](https://github.com/nuxt/nuxt/pulls?q=is%3Apr+is%3Amerged), пока мы не начнем генерировать автоматические журналы изменений в документации.
```

2024-07-01 07:19 UTC, alexeyvokin commented on content/7.blog/4.nuxt3-beta.md
> +- **2 июля, 2020**: Первый коммит Nuxt 3 с полной переписью на TypeScript
```suggestion
- **2 июля, 2020**: Первый коммит Nuxt 3, который полностью переписанный на TypeScript
```

2024-07-01 07:19 UTC, alexeyvokin commented on content/7.blog/4.nuxt3-beta.md
> +- **2 ноября, 2020**: Начальная работа над [Nuxt Nitro](https://nuxt.com/guide/concepts/server-engine)
```suggestion
- **2 ноября, 2020**: Начало работы над [Nuxt Nitro](https://nuxt.com/guide/concepts/server-engine)
```

2024-07-01 07:30 UTC, merged