feat(docs) Перевод Nuxt 2 Static Improvements
translation-gang/nuxt.com pull request #56
Opened 2024-07-02 07:45 UTC by Ibochkarev

feat(docs) Перевод Nuxt 2 Static Improvements

resolves: #30

2024-07-02 07:56 UTC, Hekikai requested changes

2024-07-02 07:56 UTC, Hekikai commented on content/7.blog/8.nuxt-static-improvements.md
> +  - name: Себастьен Шопен
```suggestion
  - name: Себастьян Шопен
```

2024-07-02 07:56 UTC, Hekikai commented on content/7.blog/8.nuxt-static-improvements.md
> +Статическая генерация наших проектов при изменении контента теперь в **~3,6 раза** быстрее 🚀
```suggestion
Статическая генерация наших проектов при изменении контента теперь в **~3.6 раза** быстрее 🚀
```

2024-07-02 07:56 UTC, Hekikai commented on content/7.blog/8.nuxt-static-improvements.md
> -::code-group
Куда пропало? Давай вернем))

2024-07-02 07:56 UTC, Hekikai commented on content/7.blog/8.nuxt-static-improvements.md
> +    `nuxt generate` будет вести себя так же, как и раньше, чтобы избежать изменений, несовместимых с предыдущими версиями, и обеспечить обратную совместимость, если вы сохраните `target: ‘server’` ил
```suggestion
`nuxt generate` будет вести себя так же, как и раньше, чтобы избежать изменений, несовместимых с предыдущими версиями, и обеспечить обратную совместимость, если вы сохраните `target: ‘server’` или не укажете совсем.
```

2024-07-02 07:56 UTC, Hekikai commented on content/7.blog/8.nuxt-static-improvements.md
> +Статическая цель:
```suggestion
Для статического режима:
```

2024-07-02 07:56 UTC, Hekikai commented on content/7.blog/8.nuxt-static-improvements.md
> +Цель сервера:
```suggestion
Для SSR:
```

2024-07-02 08:01 UTC, Ibochkarev commented on content/7.blog/8.nuxt-static-improvements.md
> -::code-group
@Hekikai  Оно не пропало, просто исправлен синтаксис

2024-07-02 13:33 UTC, alexeyvokin commented on content/7.blog/8.nuxt-static-improvements.md
> +Что делать, если вы разрабатываете модуль nuxt, который работает с файлами, которые не должны запускать повторную сборку? Лучшим примером является модуль [@nuxt/content](https://content.nuxtjs.org),
```suggestion
Что делать, если вы разрабатываете модуль nuxt, который работает с файлами, которые не должны запускать повторную сборку? Лучшим примером является модуль [@nuxt/content](https://content.nuxtjs.org), который читает файлы markdown из репозитория. В этом случае эти файлы используются в runtime-модуле, что имеет место при использовании `@nuxt/content`, сам модуль может сообщить nuxt игнорировать эти файлы для вас, так что вам не нужно ничего делать! Авторы модулей могут использовать новый хук `generate:cache:ignore` для этого:
```

2024-07-02 14:26 UTC, Hekikai commented on content/7.blog/8.nuxt-static-improvements.md
> -::code-group
Показывает, что +3 линии, точно все ок?

2024-07-03 04:29 UTC, mnenie approved these changes

2024-07-03 05:18 UTC, Hekikai approved these changes

2024-07-03 09:35 UTC, merged