Локализация content/7.blog/4.nuxt2-eol.md (#50)
translation-gang/nuxt.com pull request #63
Opened 2024-07-08 03:30 UTC by JonikUl

Resolve #50

[content/7.blog/4.nuxt2-eol.md](https://nuxt-ru.vercel.app/blog/nuxt2-eol)

2024-07-08 04:44 UTC, mnenie requested changes

2024-07-08 04:44 UTC, mnenie commented on content/7.blog/4.nuxt2-eol.md
> +Если вам нужно остаться на Nuxt 2 после EOL, мы объединились с HeroDevs, чтобы предложить Nuxt 2 Never-Ending Support (NES). Nuxt 2 NES обеспечивает постоянные исправления безопасности и совместимост
```suggestion
Если вам нужно остаться на Nuxt 2 после EOL, мы объединились с HeroDevs, чтобы предложить бесконечную поддержку Nuxt 2 (NES). Nuxt 2 NES обеспечивает постоянные исправления безопасности и совместимости для Nuxt 2 и всех официальных модулей Nuxt (модулей, выпущенных командой Nuxt, помеченных `@nuxt/...` на маркетплейсе) даже после EOL, чтобы приложения со строгими требованиями соответствия оставались безопасными и совместимыми. Это также гарантирует, что приложения Nuxt 2 продолжат эффективно работать в современных браузерах и сохранят совместимость с такими важными библиотеками, как Vue 2. Более того, Nuxt 2 NES имеет непрерывный мониторинг безопасности и SLA корпоративного уровня в отношении поддержки и исправлений.
```

2024-07-08 04:44 UTC, mnenie commented on content/7.blog/4.nuxt2-eol.md
> +Если вам нужно остаться на Nuxt 2 после EOL, мы объединились с HeroDevs, чтобы предложить Nuxt 2 Never-Ending Support (NES). Nuxt 2 NES обеспечивает постоянные исправления безопасности и совместимост
вот тут тогда просто придерживаемся переводов до

2024-07-08 05:13 UTC, Hekikai requested changes

2024-07-08 05:13 UTC, Hekikai commented on content/7.blog/4.nuxt2-eol.md
> +Перейдите через бесконечную поддержку Nuxt от HeroDevs (NES)
```suggestion
Перейдите к "бесконечной" поддержке Nuxt от HeroDevs (NES)
```

2024-07-08 05:13 UTC, Hekikai commented on content/7.blog/4.nuxt2-eol.md
> +Помимо использования Vue 3 и composition API, он поставляется с функциями и инновациями:
```suggestion
Помимо использования Vue 3 и Сomposition API, он поставляется со следующими функциями и инновациями:
```

2024-07-08 05:13 UTC, Hekikai commented on content/7.blog/4.nuxt2-eol.md
> +- Поддержка бессерверных сред (AWS Lambda, Deno, Cloudflare Workers) с минимальным холодным запуском.
```suggestion
- Поддержка бессерверных сред (AWS Lambda, Deno, Cloudflare Workers) с минимальным "холодным" запуском.
```

2024-07-08 05:13 UTC, Hekikai commented on content/7.blog/4.nuxt2-eol.md
> +- Универсальный и гибридный рендеринг: преимущества как SPA, так и SSR с детальным контролем рендеринга маршрутов
```suggestion
- Универсальный и гибридный рендеринг: преимущества как SPA, так и SSR с детальным контролем рендеринга маршрутов.
```

2024-07-08 05:13 UTC, Hekikai commented on content/7.blog/4.nuxt2-eol.md
> +- Интеграция с Vite для более быстрого опыта разработки
```suggestion
- Интеграция с Vite для более быстрого опыта разработки.
```

2024-07-08 05:13 UTC, Hekikai commented on content/7.blog/4.nuxt2-eol.md
> +- Маршруты сервера и API со сквозной типизацией на базе Nitro
```suggestion
- Маршруты сервера и API со сквозной типизацией на базе Nitro.
```

2024-07-08 05:13 UTC, Hekikai commented on content/7.blog/4.nuxt2-eol.md
> +- Автоматический импорт композаблов и утилит
```suggestion
- Автоматический импорт композаблов и утилит.
```

2024-07-08 05:13 UTC, Hekikai commented on content/7.blog/4.nuxt2-eol.md
> +- Функция слоев для разработки на основе домена
```suggestion
- Функция слоев для разработки на основе домена.
```

2024-07-08 05:43 UTC, mnenie approved these changes

2024-07-08 08:03 UTC, Hekikai approved these changes

2024-07-09 04:38 UTC, alexeyvokin approved these changes

2024-08-11 11:33 UTC, merged