Локализация content/7.blog/212.shiki-v1.md (#48)
translation-gang/nuxt.com pull request #65
Opened 2024-07-10 15:59 UTC by JonikUl

Resolve #48

[content/7.blog/212.shiki-v1.md](https://nuxt-ru.vercel.app/blog/shiki-v1)

2024-07-10 17:28 UTC, mnenie requested changes

2024-07-10 17:28 UTC, mnenie commented on content/7.blog/21.shiki-v1.md
> +Nuxt прилагает много усилий для продвижения [веба на распределенные серверы](/blog/nuxt-on-the-edge), делая веб более доступным с меньшей задержкой и лучшей производительностью. Как и серверы CDN, сл
```suggestion
Nuxt прилагает много усилий для продвижения [веба на распределенные серверы](/blog/nuxt-on-the-edge), делая веб более доступным с меньшей задержкой и лучшей производительностью. Как и серверы CDN, службы граничного хостинга, такие как [CloudFlare Workers](https://workers.cloudflare.com/), развернуты по всему миру. Пользователи получают контент с ближайшего сервера без необходимости совершать путешествие на исходный сервер, который может находиться за тысячи миль. Наряду с потрясающими преимуществами, которые они предоставляют, они также идут на некоторые компромиссы. Например, периферийные серверы используют ограниченное runtime-окружение. CloudFlare Workers также не поддерживает доступ к файловой системе и обычно не сохраняет состояние между запросами. Хотя основные накладные расходы Shiki заключаются в предварительной загрузке грамматик и тем, это не будет хорошо работать в периферийной среде.
```

2024-07-10 17:28 UTC, mnenie commented on content/7.blog/21.shiki-v1.md
> +Все началось с чата между [Себастьеном](https://twitter.com/Atinux) и мной. Мы пытались сделать [Nuxt Content](https://github.com/nuxt/content), который использует Shiki для подсветки блоков кода, дл
```suggestion
Все началось с чата между [Себастьеном](https://twitter.com/Atinux) и мной. Мы пытались сделать [Nuxt Content](https://github.com/nuxt/content), который использует Shiki для подсветки блоков кода, для работы на периферии.
```

2024-07-10 17:28 UTC, mnenie commented on content/7.blog/21.shiki-v1.md
> +Нам было нужно обернуть JSON-файлы в ESM в виде встроенного литерала, чтобы мы могли использовать [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) для
```suggestion
Нам нужно было обернуть JSON-файлы в ESM в виде встроенного литерала, чтобы мы могли использовать [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) для их динамического импорта. Разница в том, что `import()` — это стандартная функция JavaScript, которая работает везде, в то время как `fs.readFile` — это API, специфичный для Node.js, который работает только в Node.js. Наличие `import()` статически также позволило бы сборщикам, таким как [Rollup](https://rollupjs.org/) и [webpack](https://webpack.js.org/), создавать граф взаимосвязей модулей и [выдавать связанный код в виде чанков](https://rollupjs.org/tutorial/#code-splitting).
```

2024-07-10 17:28 UTC, mnenie commented on content/7.blog/21.shiki-v1.md
> +Нам было нужно обернуть JSON-файлы в ESM в виде встроенного литерала, чтобы мы могли использовать [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) для
так как будто лучше звучит

2024-07-10 17:40 UTC, mnenie requested changes

2024-07-10 17:40 UTC, mnenie commented on content/7.blog/21.shiki-v1.md
> +Поддержка темного/светлого режима [была часто запрашиваемой функцией](https://github.com/shikijs/shiki/issues/33). Из-за статического подхода, который использует Shiki, невозможно было менять тему на
```suggestion
Поддержка темного/светлого режима [была часто запрашиваемой функцией](https://github.com/shikijs/shiki/issues/33). Из-за статического подхода, который использует Shiki, невозможно было менять тему на лету при рендеринге. Решение в прошлом состояло в том, чтобы дважды генерировать HTML с подсветкой и переключать его видимость на основе предпочтений пользователя — это было неэффективно, так как дублировало payload или использовало [CSS переменные темы](https://github.com/shikijs/shiki/pull/212), что теряло гранулярную подсветку, для которой Shiki отлично подходит. С новой архитектурой Shikiji я сделал шаг назад, переосмыслил проблему и [придумал идею](https://github.com/shikijs/shiki/issues/33#issuecomment-1676362336) разбить общие токены и объединить несколько тем как встроенные переменные CSS, которые обеспечивают эффективный вывод, при этом согласуясь с философией Shiki. Вы можете узнать больше об этом в [документации Shiki](https://shiki.style/guide/dual-themes).
```

2024-07-10 17:40 UTC, mnenie commented on content/7.blog/21.shiki-v1.md
> +Мы также воспользовались шансом пересмотреть интеграции Twoslash, когда переписывали Shikiji, попробовать ["dog-fooding"](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) и проверить расширяем
```suggestion
Мы также воспользовались шансом пересмотреть интеграции Twoslash, когда переписывали Shikiji, попробовать ["dog-fooding"](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) и проверить расширяемость. С новым внутренним HAST мы можем [интегрировать Twoslash как плагин-трансформер](https://shiki.style/packages/twoslash), что делает его работающим везде, где работает Shiki, а также использовать в виде композабла с другими трансформерами.
```

2024-07-11 03:19 UTC, mnenie approved these changes

2024-07-15 02:59 UTC, alexeyvokin commented on content/7.blog/21.shiki-v1.md
> +[Twoslash](https://github.com/twoslashes/twoslash) — это инструмент интеграции для извлечения информации о типе из [TypeScript Language Services](https://github.com/microsoft/TypeScript/wiki/Using-th
Orta Therox - это имя и фамилия? не переводим?

2024-07-15 05:16 UTC, JonikUl commented on content/7.blog/21.shiki-v1.md
> +[Twoslash](https://github.com/twoslashes/twoslash) — это инструмент интеграции для извлечения информации о типе из [TypeScript Language Services](https://github.com/microsoft/TypeScript/wiki/Using-th
@alexeyvokin Наверное нужно перевести, раз везде имена переводим. 
Орта Терокс - так наверное?
Только это мужчина. В таком случае сделан (кем) - Ортой Тероксом?

Мистраль подсказал что вот так:
Транслитерация: Орта Терокс
```
Склонение по падежам:

Именительный падеж: Орта Терокс
Родительный падеж: Орты Терокса
Дательный падеж: Орте Тероксу
Винительный падеж: Орту Терокса
Творительный падеж: Ортой Тероксом
Предложный падеж: Орте Тероксе
```

2024-07-15 07:47 UTC, alexeyvokin commented on content/7.blog/21.shiki-v1.md
> +[Twoslash](https://github.com/twoslashes/twoslash) — это инструмент интеграции для извлечения информации о типе из [TypeScript Language Services](https://github.com/microsoft/TypeScript/wiki/Using-th
@Hekikai согласен?

2024-07-15 08:06 UTC, Hekikai commented on content/7.blog/21.shiki-v1.md
> +[Twoslash](https://github.com/twoslashes/twoslash) — это инструмент интеграции для извлечения информации о типе из [TypeScript Language Services](https://github.com/microsoft/TypeScript/wiki/Using-th
Да, годно! Оставляем) Поддержу глоссарий в телеге

2024-07-15 10:13 UTC, alexeyvokin approved these changes

2024-08-11 11:40 UTC, Ibochkarev approved these changes

2024-08-11 11:49 UTC, merged