Локализация content/7.blog/18.nuxt-devtools-v1-0.md
translation-gang/nuxt.com pull request #68
Opened 2024-07-13 08:18 UTC by JonikUl

Resolve #44 

[content/7.blog/18.nuxt-devtools-v1-0.md](https://nuxt-ru.vercel.app/blog/nuxt-devtools-v1-0)

2024-07-13 08:46 UTC, mnenie requested changes

2024-07-13 08:46 UTC, mnenie commented on content/7.blog/18.nuxt-devtools-v1-0.md
> +Обычные абстракции — это отличные вещи для переноса сложности реализации и упрощения фокусировки при сборке. С другой стороны, они также могут добавить дополнительную нагрузку на пользователей, чтобы
```suggestion
Обычные абстракции — это отличные вещи для переноса сложности реализации и упрощения фокусировки при сборке. С другой стороны, они также могут добавить дополнительную нагрузку на пользователей, чтобы изучить и понять, что происходит под капотом. Это также приводит к неявности, например, откуда автоматически импортируется компонент или сколько модулей используют определенный компонент и т.д. Это также может затруднить отладку.
```

2024-07-13 08:46 UTC, mnenie commented on content/7.blog/18.nuxt-devtools-v1-0.md
> +- **Избегайте смещений макета** - Наличие DevTools в виде плавающей панели позволит избежать смещений макета при переключении DevTools.
вот тут звучит хорошо "смещений макета", но предлагаю придерживаться глоссария и использовать лэйаут, что думаете ?

2024-07-13 08:46 UTC, mnenie commented on content/7.blog/18.nuxt-devtools-v1-0.md
>  :article-video{cloudinary="v1700132395/devtools/3-imports_qhahdf"}
тут норм будет отображаться если не пропущена строка перед этим ?

2024-07-13 08:46 UTC, mnenie commented on content/7.blog/18.nuxt-devtools-v1-0.md
> +Вкладка Assets показывает все статические ассеты в вашем каталоге `public`. Она поддерживает предварительный просмотр изображений, видео, шрифтов, PDF-файлов и других файлов, URL-адрес или фрагмент к
```suggestion
Вкладка Assets показывает все статические ассеты в вашей директории `public`. Она поддерживает предварительный просмотр изображений, видео, шрифтов, PDF-файлов и других файлов, URL-адрес или фрагмент кода которых вы можете легко скопировать для использования в своем приложении. Вы также можете перетаскивать файлы, чтобы загружать их напрямую из Nuxt DevTools.
```

2024-07-13 08:57 UTC, mnenie requested changes

2024-07-13 08:57 UTC, mnenie commented on content/7.blog/18.nuxt-devtools-v1-0.md
> +Хотя Nuxt DevTools в основном сосредоточен на предоставлении инструментов разработки, иногда нам может понадобиться узнать, как чанки компонуются в продакшене. Build Analyzer позволяет вам запустить
```suggestion
Хотя Nuxt DevTools в основном сосредоточен на предоставлении инструментов разработки, иногда нам может понадобиться узнать, как чанки компонуются в продакшене. Build Analyzer позволяет вам запустить продакшен-сборку и проанализировать чанки и модули в любое время, а также увидеть, как они связаны. Вы также можете сделать несколько сборок на разных ветках, чтобы сравнить, как ваш рефакторинг/изменения влияют на размер пакета и т.д.
```

2024-07-13 08:57 UTC, mnenie commented on content/7.blog/18.nuxt-devtools-v1-0.md
>  Nuxt provides a very convenient way to create server API functions with the [server routes](/docs/guide/directory-structure/server#server-routes). Since in Nuxt we have that information, we are able
вот тут осталось лишнее, снизу переведено )

2024-07-13 08:57 UTC, mnenie commented on content/7.blog/18.nuxt-devtools-v1-0.md
> +Nuxt предоставляет очень удобный способ создания серверных API функций помощью [роутов сервера](/docs/guide/directory-structure/server#server-routes). Поскольку в Nuxt у нас есть эта информация, мы м
```suggestion
Nuxt предоставляет очень удобный способ создания серверных API функций с помощью [роутов сервера](/docs/guide/directory-structure/server#server-routes). Поскольку в Nuxt у нас есть эта информация, мы можем предоставить вам площадку для тестирования и отладки функций API сервера, похожую на инструменты вроде Postman. Мы автоматически перечисляем все API сервера, доступные в приложении. И мы выполняем эти функции **в контексте вашего приложения**, поэтому вам не нужно вручную настраивать их во внешних инструментах. Как всегда, у нас также есть фрагменты кода, которые вы можете скопировать и вставить в свое приложение.
```

2024-07-13 13:56 UTC, JonikUl commented on content/7.blog/18.nuxt-devtools-v1-0.md
> +- **Избегайте смещений макета** - Наличие DevTools в виде плавающей панели позволит избежать смещений макета при переключении DevTools.
@mnenie честно говоря я не знаю, мне не резануло взгляд потому что в google page speed CLS (а тут именно об этой метрике речь как я понял) переводят именно как смещение макета страницы) можно и лейаут наверное.

2024-07-13 13:59 UTC, mnenie commented on content/7.blog/18.nuxt-devtools-v1-0.md
> +- **Избегайте смещений макета** - Наличие DevTools в виде плавающей панели позволит избежать смещений макета при переключении DevTools.
ну тогда можно оставить и смещение макета ))

2024-07-14 04:41 UTC, JonikUl commented on content/7.blog/18.nuxt-devtools-v1-0.md
> +- **Избегайте смещений макета** - Наличие DevTools в виде плавающей панели позволит избежать смещений макета при переключении DevTools.
Хорошо))

2024-07-14 04:41 UTC, JonikUl commented on content/7.blog/18.nuxt-devtools-v1-0.md
>  :article-video{cloudinary="v1700132395/devtools/3-imports_qhahdf"}
Поправил)

2024-07-14 04:58 UTC, mnenie approved these changes

2024-07-16 05:37 UTC, Ibochkarev approved these changes

2024-08-11 11:50 UTC, merged