feat(docs) Добавлен перевод Exploring Different Features of the Fetch…
translation-gang/nuxt.com pull request #82
Opened 2024-09-16 02:56 UTC by Ibochkarev

resolves: #28

2024-09-16 07:02 UTC, Hekikai requested changes

2024-09-16 07:02 UTC, Hekikai commented on content/7.blog/7.understanding-how-fetch-works-in-nuxt-2-12.md
> -## Fetch before Nuxt 2.12
Тут что-то сбилось, одну строчку потерял, проверь, пожалуйста

2024-09-16 07:02 UTC, Hekikai commented on content/7.blog/7.understanding-how-fetch-works-in-nuxt-2-12.md
> +Если вы работали с Nuxt какое-то время, то знаете, что предыдущая версия `fetch` была значительно отлична.
```suggestion
Если вы работали с Nuxt какое-то время, то знаете, что предыдущая версия `fetch` значительно отличалась.
```

2024-09-16 07:02 UTC, Hekikai commented on content/7.blog/7.understanding-how-fetch-works-in-nuxt-2-12.md
> +**После -** Мы можем получить доступ к контексту `this`, как и в хуках Vue на клиенте, без передачи каких-либо параметров.
```suggestion
**После -** Мы можем получить доступ к контексту `this` как и в хуках Vue на клиенте без передачи каких-либо параметров.
```

2024-09-17 01:21 UTC, Ibochkarev commented on content/7.blog/7.understanding-how-fetch-works-in-nuxt-2-12.md
> -## Fetch before Nuxt 2.12
Проверил - все ок!

2024-09-17 01:21 UTC, merged